### ISSUE TITLE
What is the base branch should be in mr?

### ISSUE THREAD

**Issue by IrenJones** [sevryukov/DBOpt_Course_PaymentData#1]
Хотелось бы узнать - у нас у каждого будет своя ветка в этом репозитории (например, совпадающая с фамилией)?
Или создать папку со своей фамилией и заливать туда все выполненные задания?

**Comment by sevryukov** [comment]
Достаточно сделать форк и предлагать свои Pull request. Ветвить пока не намеревался, но практика покажет.

**Comment by sevryukov** [comment]
@IrenJones Уточню свой ответ: своё решение (патч) Вы можете оформлять как угодно: модификация имеющегося в репозитории SQL скрипта, создание отдельного скрипта в корне репозитария или в отдельной папке со своим патчем (скриптом).
В конечном виде мы должны получить просто рабочее решение (на основе всех предложенных изменений). Если что-то пойдёт не так, то будем обсуждать в Issue или на парах.
