### ISSUE TITLE
Проблема создания ролей на уровне СУБД

### ISSUE THREAD

**Issue by NIKKAS29** [sevryukov/DBOpt_Course_PaymentData#12]
Были предприняты попытки создания новой роли/пользователя через обозреватель объектов во вкладке "Безопасность" и путем исполнения скрипта вида CREATE ROLE ... , чтобы затем каждой роли путем операций GRANT ALL ... описать перечень разрешений о допуске выполнения операции чтения/записи в определенные таблицы. Но ни гугление, ни методы тыка не привели к созданию ролей, а лишь получение ошибки о недостатке прав для выполнения такой операции.

**Comment by sevryukov** [comment]
@NIKKAS29 Уточните, пожалуйста, по какой инструкции Вы действовали и на каком её шаге возникла ошибка (исключение) и какая.
