### ISSUE TITLE
Необходимость индексов в задачах первого уровня

### ISSUE THREAD

**Issue by veotani** [sevryukov/DBOpt_Course_PaymentData#13]
@sevryukov Сергей Юрьевич, подскажите пожалуйста, может ли получиться так, что в первой задаче не нужно создавать индексы? Мы рассмотрели планы выполнения запросов для:

1. Операции вставки в таблицу `Payment`
2. Операций, которые присутствуют в триггере для `INSERT` и `UPDATE` для таблицы `Payment` по отдельности.
3. Функций, которые присутствуют в триггерах - разбивали на несколько частей их код на несколько частей, как мы делали на парах.

Каждый план показал, что листья деревьев, отображающих план запроса, содержат операции поиска и вставки в кластерный индекс. Насколько я понимаю, создание нового индекса не улучшит производительность этого запроса (и его частей). Возможен ли такой исход?

На данный момент вставка 50 строк занимает 8 секунд.

Спасибо.

**Comment by sevryukov** [comment]
При соответствующей аргументации возможно.
