### ISSUE TITLE
Проблемы по работе с триггером по расчету баланса

### ISSUE THREAD

**Issue by Snezzz** [sevryukov/DBOpt_Course_PaymentData#15]
Перед возникновением проблемы: произведен перевод скрипта PaymentData.sql на диалект PostgreSQL вручную.
**Проблема**: при работе с тригерром T_PaymentParticipant_BU. В переводе что-то сделано неверно, потому что возникает ошибка бесконечного цикла по UPDATE. 
**Вопрос**: как правильно это делается в PostgreSQL? Гуглили, пытались решить проблему, но безрезультатно.
Код:
```
СREATE OR REPLACE FUNCTION T_PaymentParticipant_BU() RETURNS TRIGGER
AS $$
BEGIN
   UPDATE paymentdata.public.PaymentParticipant
      SET
        balance = public.F_CalculatePaymentParticipantBalance(NEW.oid)
      ,name = NEW.Name
     ,optimisticlockfield = NEW.OptimisticLockField
      ,gcrecord = NEW.GCRecord
      ,objecttype = NEW.ObjectType
      ,activefrom = NEW.ActiveFrom
      ,inactivefrom = NEW.InactiveFrom
      ,bankdetails = NEW.BankDetails
	  , balance2 = NEW.Balance2,
     balance3 = new.balance3
   where paymentdata.public.PaymentParticipant.oid = NEW.oid;
 --RETURN new;
END
  $$ VOLATILE LANGUAGE plpgsql;

CREATE TRIGGER PaymentParticipant_BU BEFORE UPDATE
ON PaymentParticipant
  for EACH row
EXECUTE PROCEDURE T_PaymentParticipant_BU();
```

**Comment by sevryukov** [comment]
@Snezzz 
1. Вопрос задан не точно. "Это делается" - это о чём? Нужна чёткая постановка задачи.
2. В MS SQL Server before **INSTED OF** триггер замещает целевой запрос. В приведённом тексте определения не вижу этой аналогии.
3. Если возникает рекурсия, то ею можно управлять (выяснять какой уровень вложенного вызова триггера имеет место быть и принимать решение). Дайте, пожалуйста, знать, если не найдёте информации об этом и нужна будет дополнительная консультация.
4. Смущает закомментированное `--RETURN new`.
5. Если говорить о практике взаимодействия в GitHub, то изменённый код (вызвавший вопросы) должен быть в репозитории (а не в Issue), а вопрос можно задать в Pull Request.
6. В случае СУБД (любого производителя) возможности и поведение могут отличаться от версии. Поэтому важно указывать не только тип (производителя) СУБД, но и версию.

**Comment by sevryukov** [comment]
@Snezzz Пожалуйста, укажите способ решения проблемы и те детали, которые я попросил (версию, к примеру). Это поможет другим участникам решать подобные проблемы.

**Comment by Snezzz** [comment]
@sevryukov 
Проблема не решена. Группой, что занимается текущим проектом, было принято решение работать с исходным скриптом в Microsoft SQL Management Studio и не переходить на PostgreSQL(10.5).

**Comment by sevryukov** [comment]
Понятно. Будет здорово, если останется время и вы попробуете вернуться к задачи портирования и её получится решить.
