### ISSUE TITLE
Портирование на MySQL

### ISSUE THREAD

**Issue by MordaCap** [sevryukov/DBOpt_Course_PaymentData#2]
Здравствуйте. 
Вопрос по заданию. У меня стоит MySQL. Вы в задании писали об адаптации на другие субд. 
В скрипте 1000+ строк. Адаптация вручную мной не рассматривалась. Нашел сервис, который адаптирует этот скрипт под mysql, но он этого не сделал. В среде есть возможность миграции базы, но для этого мне нужно подключиться к серверу, откуда мигрировать ее. Решил попробовать поставить mssql server, но моя система не соответствует требованиям. 

Могу ли я подключиться к вам и мигрировать базу? Иначе единственным выходом вижу с нуля ее переписывать.

**Comment by sevryukov** [comment]
@MordaCap Уточните, пожалуйста, каким инструментом Вы пользовались для конвертации и какую систему (ОС) Вы используете?
Используете ли Вы в своей работе docker?

**Comment by MordaCap** [comment]
http://www.sqlines.com/online - для перевода запроса. 
win7, а для ms sql server'а нужна 8+ 
Нет, docker не использую.

**Comment by sevryukov** [comment]
Прошу прислать ссылку на источник на основе которого Вы сделали вывод о необходимости использования ОС 8+
Скорее всего это вот эта [статья](https://docs.microsoft.com/ru-ru/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server).

Если Вы не планируете обновление ОС до 10-ки, то рекомендую воспользоваться 2014-й версий SQL Server ([требования](https://msdn.microsoft.com/library/ms143506(v=sql.120).aspx#%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%BA%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D1%80%D1%83,%20%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%B8%20%D0%B8%20%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B9%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5)).

**Comment by sevryukov** [comment]
@MordaCap Проблему можно считать закрытой или нужна ещё какая-нибудь помощь?

**Comment by MordaCap** [comment]
Простите, ответ прочитал вчера перед отъездом в Моксву. 
Думаю, что возьму виртуальную машину azure и там подниму ms sql server, и оттуда мигрирую. 
Только 5 числа приеду. Как сделаю отпишусь сюда.

**Comment by sevryukov** [comment]
@MordaCap Скорее всего для полноценной миграции под MySQL Вам придётся переписать триггера и функции. Предлагаю прежде чем приступать к этому выполнить оценку трудоёмкости и возможности такой миграции. Возможно, что на данном этапе окажется проще использовать SQL Server 2014 или более ранней версии.
Впрочем, мне будет интересно получить от Вас и коллег аналогичный стенд под управлением MySQL - появится возможность сравнивать поведение разных СУБД в одной и той же задаче.

**Comment by MordaCap** [comment]
Посмотрим. Оценка сложности изначально была не в мою пользу. Но хочется сделать именно так.

**Comment by sevryukov** [comment]
Всё бы ничего, если бы этот вопрос так долго не решался.
Как и писал ранее - в Вашем случае есть возможность поставить SQL Server 2014 и заняться целевыми задачами.
