### ISSUE TITLE
Уточнение задания

### ISSUE THREAD

**Issue by RomaKoks** [sevryukov/DBOpt_Course_PaymentData#3]
Вероятно, я спешу с выводами и стоило бы сначала глубже посмотреть на вид БД, но у меня есть стойкое ощущение, что индекс либо почти не влияет, либо наоборот замедляет вставку, так как обычно, при переносе данных быстрее скопировать без индекса, а потом его построить заново.

**Comment by sevryukov** [comment]
Да, @RomaKoks, возможно Вы спешите с выводами, но может оказаться и так, что индексы не ускорят работу запросов (и даже замедлят).  Можно попробовать доказать и аналитически (без тестов) - не возражаю.
Обратите внимание на присутствующие триггеры и функции - они могут быть источником проблем с производительностью (это мы обсуждали на встрече с коллегами). Индексы могут потребоваться для оптимизации именно их.

**Comment by RomaKoks** [comment]
Supplier 
  
ProfitByMaterialAsPayer bit NULL, -- Если установлен данный влаг, то при расчёте баланса по материалам учитываются платежи с этм поставщиком в роли плательщика как доход
  ProfitByMaterialAsPayee bit NULL, -- Если установлен данный влаг, то при расчёте баланса по материалам учитываются платежи с этм поставщиком в роли получателя платежа как доход
  CostByMaterialAsPayer bit NULL, -- Если установлен данный влаг, то при расчёте баланса по материалам учитываются платежи с этм поставщиком в роли плательщика как расход

только один из флагов может быть установлен или может быть несколько?

**Comment by sevryukov** [comment]
@RomaKoks Предлагаю не прямой ответ на вопрос, а рассуждение.
1. Если верить предоставленной схеме данных, то возможна любая комбинация заполнения полей.
2. Если обратить внимание на название полей, то кажется сомнительным иметь флаги одновременно в ProfitByMaterialAsPayer и CostByMaterialAsPayer
3. Интересно, как ответ на поставленный вопрос связан с поставленной задачей (не сомневаюсь, что связь м.б., потому и интересуюсь).

**Comment by RomaKoks** [comment]
Связь примерно такая:
- наша задача сгенерировать данные;
- при расчете балансов эти поля используются; 
- нам необходимо как-то проверить корректность расчетов баланса.

И все-таки какой прямой ответ? ProfitByMaterialAsPayer и CostByMaterialAsPayer гипотетически могут быть одновременно, если поставщику от компании тоже нужны какие-то материалы, как мне кажется.

**Comment by sevryukov** [comment]
@RomaKoks В том-то и дело, что корректность расчёта баланса на основе данных генератора не зависит от ответа на Ваш вопрос. И да, Ваше допущение о том, что компания может продать материалы поставщику уместно и в этом случае можно допустить флаги, указанные Вами.

Анализ кода показывает, что эти флаги используются в функции `F_CalculateBalanceByMaterial`, что упрощает проверку на корректность.

Прямой ответ есть в коде. Как я уже отмечал, ограничений на комбинации нет.
Однако на практике, либо флаг ставится в поле ProfitByMaterialAsPayer (в описании формул это те самые "Буфер ..."), либо в два других одновременно.

Мы с Вами должны научиться проверять код, а не домыслы вокруг кода. Это не всегда легко, понимаю.

**Comment by RomaKoks** [comment]
Для того чтобы проверить корректность расчета балансов необходимо понять что вообще нужно проверить...а из имеющегося в pdf описания лично мне мало что понятно...При чем там Петрович, Энергодом, Магазин, Переход года, СТРИНКО итд. 
Понятно что написано в функции, непонятно что проверять.
Есть более понятное описание в терминах таблиц и полей имеющейся бд?

**Comment by sevryukov** [comment]
@RomaKoks Мы с Вами повторяемся.
В скрипте есть достаточное описание таблиц и полей (Вы ведь нашли комментарии к полям, раз их цитируете). В скрипте нет никаких ограничений на то, какие допустимы комбинации значений флагов, а значит Вы смело можете проверять все возможные комбинации, хотя я этого и не прошу.
Полагаю, что достаточно будет таких тестов: "При добавлении платежа с указанием такого-то объекта работ, такого-то поставщика и такой-то кассы, объект по материалам принимает значение, равное сумме платежа со знаком минус".
В общем я не прошу проверить все возможные комбинации, а прошу 
> Разаботать простой тест на корректность расчёта баланса

Акцент в работе ставится не на тестировании логики, а на оптимизации (из наших рассуждений я пока вообще не вижу связи между сочетанием значений в полях и оптимизацией, но не отрицаю, что такая связь Вами может быть обнаружена).

Предлагаю действовать итерационно - представите первый результат, будет легче обсуждать вопросы и детали.
